[book]
authors = ["TFC"]
language = "en"
multilingual = false
src = "src"
title = "笔记本"

[rust]
edition = "2021"

[output.html.playground]
editable = true
copyable = true
copy-js = true
line-numbers = true
runnable = true

[output.html.print]
enable = true
page-break = true # 插入分页

[output.html]
# github图标
git-repository-url = "https://github.com/iqdxa/iqdxa.github.io"
git-repository-icon = "fa-github"
# 编辑按钮
edit-url-template = "https://github.com/iqdxa/iqdxa.github.io/edit/main/{path}"



